"""
Artifact Routes

API endpoints for accessing artifacts generated during pipeline execution.
Slice 9: Download artifacts, view artifact content, list artifacts.
"""

from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Response, Query, status
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from src.db.database import get_db
from src.models.schemas import (
    ArtifactContentResponse,
    ArtifactListResponse,
    ArtifactMetadata,
    ArtifactSummary,
)
from src.services.artifact_service import ArtifactService


# Create router
router = APIRouter()


@router.get(
    "/{artifact_id}",
    response_model=ArtifactMetadata,
    summary="Get artifact metadata",
    description="Get metadata for a specific artifact including file information.",
)
def get_artifact(
    artifact_id: str,
    session: Session = Depends(get_db),
) -> ArtifactMetadata:
    """
    Get artifact metadata.

    Returns information about an artifact including its file path,
    size, format, and whether it has been promoted to permanent storage.
    """
    artifact = ArtifactService.get_artifact_metadata(session, artifact_id)

    if not artifact:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Artifact with ID '{artifact_id}' not found",
        )

    return ArtifactMetadata(**artifact)


@router.get(
    "/{artifact_id}/content",
    response_model=ArtifactContentResponse,
    summary="Get artifact content for preview",
    description="Get the content of an artifact file for preview (text-based formats only).",
)
def get_artifact_content(
    artifact_id: str,
    session: Session = Depends(get_db),
) -> ArtifactContentResponse:
    """
    Get artifact content for preview.

    Returns the file content for text-based formats (json, md, txt, py, html, csv, mmd).
    Binary files or files larger than 1MB will return an error instead.
    """
    content_data = ArtifactService.get_artifact_content(session, artifact_id)

    if not content_data:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Artifact with ID '{artifact_id}' not found",
        )

    return ArtifactContentResponse(**content_data)


@router.get(
    "/{artifact_id}/download",
    summary="Download artifact file",
    description="Download an artifact file directly.",
)
def download_artifact(
    artifact_id: str,
    session: Session = Depends(get_db),
) -> FileResponse:
    """
    Download an artifact file.

    Streams the artifact file directly to the client for download.
    """
    file_path = ArtifactService.get_artifact_file_path(session, artifact_id)

    if not file_path:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Artifact with ID '{artifact_id}' not found",
        )

    path = Path(file_path)

    if not path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Artifact file not found at {file_path}",
        )

    # Get artifact for filename
    artifact = ArtifactService.get_artifact(session, artifact_id)
    if artifact:
        # Create filename with version info: artifact_name_v1.json
        filename = f"{artifact.artifact_name}_{artifact_id}.{artifact.format}"
    else:
        filename = path.name

    # Determine media type
    media_type_map = {
        "json": "application/json",
        "md": "text/markdown",
        "mmd": "text/markdown",
        "txt": "text/plain",
        "py": "text/x-python",
        "html": "text/html",
        "csv": "text/csv",
    }
    media_type = media_type_map.get(artifact.format if artifact else "txt", "application/octet-stream")

    return FileResponse(
        path=str(path),
        filename=filename,
        media_type=media_type,
    )


@router.get(
    "/execution/{execution_id}",
    response_model=ArtifactListResponse,
    summary="List artifacts for an execution",
    description="List all artifacts generated by a specific checkpoint execution.",
)
def list_execution_artifacts(
    execution_id: str,
    session: Session = Depends(get_db),
) -> ArtifactListResponse:
    """
    List all artifacts for a checkpoint execution.

    Returns metadata for all artifacts generated during the execution,
    including those in staging and promoted to permanent storage.
    """
    artifacts = ArtifactService.list_artifacts_for_execution(session, execution_id)

    return ArtifactListResponse(
        execution_id=execution_id,
        artifacts=[ArtifactSummary(**art) for art in artifacts],
    )
